<template><div><h2 id="final-shell-安装" tabindex="-1"><a class="header-anchor" href="#final-shell-安装"><span>Final-shell 安装</span></a></h2>
<h2 id="x-ui面板安装" tabindex="-1"><a class="header-anchor" href="#x-ui面板安装"><span>X-ui面板安装</span></a></h2>
<p>通过x-ui安装trojan 保证的不填好用 ，fallback 回落不生效</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" data-title="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> &#x3C;(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -Ls</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://raw.githubusercontent.com/vaxilu/x-ui/master/install.sh)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="域名申请" tabindex="-1"><a class="header-anchor" href="#域名申请"><span>域名申请</span></a></h2>
<p><a href="https://www.namesilo.com/?rid=3853d48oc" target="_blank" rel="noopener noreferrer">https://www.namesilo.com/?rid=3853d48oc</a></p>
<h2 id="证书申请" tabindex="-1"><a class="header-anchor" href="#证书申请"><span>证书申请</span></a></h2>
<h3 id="acme-sh工具下载" tabindex="-1"><a class="header-anchor" href="#acme-sh工具下载"><span>acme.sh工具下载</span></a></h3>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" data-title="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> https://get.acme.sh</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sh</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> email=ethanwu302@gmail.com</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="独立模式申请" tabindex="-1"><a class="header-anchor" href="#独立模式申请"><span>独立模式申请</span></a></h3>
<p>需要保证</p>
<ul>
<li>域名对应的ip是ok的</li>
<li>80端口是空闲的</li>
</ul>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" data-title="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">acme.sh</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --issue</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -d</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> notm.top</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --standalone</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --force</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="证书安装" tabindex="-1"><a class="header-anchor" href="#证书安装"><span>证书安装</span></a></h3>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" data-title="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">acme.sh</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --install-cert</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -d</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> notm.top</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> \</span></span>
<span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">  --key-file</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /root/ca/server.key</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">  \</span></span>
<span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">  --fullchain-file</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /root/ca/server.crt</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="证书自动更新" tabindex="-1"><a class="header-anchor" href="#证书自动更新"><span>证书自动更新</span></a></h3>
<p>默认自动开启定时任务更新 ，通过crontab -l 查看，删除后可以通过以下命令添加</p>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>acme.sh  --install-cronjob</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="安装trojan" tabindex="-1"><a class="header-anchor" href="#安装trojan"><span>安装trojan</span></a></h2>
<h3 id="获取脚本" tabindex="-1"><a class="header-anchor" href="#获取脚本"><span>获取脚本</span></a></h3>
<p>版本选择 	 <a href="https://github.com/p4gefau1t/trojan-go/releases" target="_blank" rel="noopener noreferrer">https://github.com/p4gefau1t/trojan-go/releases</a></p>
<p>wget 	 <a href="https://github.com/p4gefau1t/trojan-go/releases/download/v0.10.6/trojan-go-linux-386.zip" target="_blank" rel="noopener noreferrer">https://github.com/p4gefau1t/trojan-go/releases/download/v0.10.6/trojan-go-linux-386.zip</a></p>
<h3 id="启动" tabindex="-1"><a class="header-anchor" href="#启动"><span>启动</span></a></h3>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>nohup ./trojan-go -server -remote 127.0.0.1:80 -local 0.0.0.0:443 -key /root/ca/server.key -cert /root/ca/server.crt -password SFe8tvHQVm >nohup.out 2>&#x26;1 &#x26;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>nohup ./trojan-go -server -remote 127.0.0.1:2017  -local 0.0.0.0:443 -key /root/ca/server.key -cert /root/ca/server.crt -password SFe8tvHQVm &gt;nohup.out 2&gt;&amp;1 &amp;</p>
<p><a href="http://129.226.216.247:2017/" target="_blank" rel="noopener noreferrer">http://129.226.216.247:2017/</a></p>
</div></template>


